name: Sync to public gocep

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git config
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Add public repo as remote
        run: |
          git remote add public https://${{ secrets.GITHUB_TOKEN }}@github.com/jeffotoni/gocep.git

      - name: Push to public master
        run: |
          git push public main:master --force-with-lease