version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.20.1
    steps:
      - checkout
      - run: make deps
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - build
