name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
        
    - name: Run tests
      run: |
        go test -coverprofile=coverage.out ./...

    - name: Submit coverage to Coveralls
      uses: coverallsapp/github-action@master
      with:
        repo-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        flags: -v
        file: coverage.out
        github-token: ${{ secrets.TOKEN_GITHUB }}
