name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1
        
    - name: Run tests
      run: |
        go test -v -tags musl -covermode atomic -coverprofile=coverage.out ./...
    - name: Submit coverage to Coveralls
      uses: coverallsapp/github-action@mad-it
      with:
        repo-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        path-to-lcov: coverage.out
        github-token: ${{ secrets.github_token }}
