name: Simple Sync from jeffotoni/gocep

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git config
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Add upstream and merge
        run: |
          git remote add upstream https://github.com/jeffotoni/gocep.git
          git fetch upstream master
          
          # Merge favorecendo sempre o upstream em casos de conflito
          git merge upstream/master --allow-unrelated-histories --strategy-option=theirs -m "sync: merge from public master"

      - name: Push to private main
        run: |
          git push origin main