name: Sync from jeffotoni/gocep

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git config
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Add public repo as remote and fetch
        run: |
          git remote add upstream https://github.com/jeffotoni/gocep.git
          git fetch upstream

      - name: Smart merge from public repo
        run: |
          if git show-ref --verify --quiet refs/remotes/upstream/master; then
            echo "🔄 Merging from upstream/master..."
            git merge upstream/master --allow-unrelated-histories -m "sync: merge from public master"
          elif git show-ref --verify --quiet refs/remotes/upstream/main; then
            echo "🔄 Merging from upstream/main..."
            git merge upstream/main --allow-unrelated-histories -m "sync: merge from public main"
          else
            echo "❌ No main branch found in upstream!"
            git branch -r
            exit 1
          fi

      - name: Push to private main
        run: |
          git push origin main